app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('app/<int:id>/<slug>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('<int:id>/post_edit/', views.post_edit, name='post_edit'),
    path('<int:id>/post_delete/', views.post_delete, name='post_delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

facebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('login/', views.user_login, name='user_login'),
    path('fb_login/', views.fb_login, name='fb_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),

    path('oauth/', include('social_django.urls', namespace='social')),
    path('like/', views.like_post, name='like_post'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
import math
from cloudinary.models import CloudinaryField


class Post(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,  on_delete=models.CASCADE)
    body = models.CharField(max_length=500)
    slug = models.SlugField(max_length=120)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    restrict_comment = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('post_detail', args=[self.id, self.slug])

    def whenpublished(self):
        now = timezone.now()

        diff = now - self.created

        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            seconds = diff.seconds

            if seconds == 1:
                return str(seconds) + "s."

            else:
                return str(seconds) + " s."

        if diff.days == 0 and diff.seconds >= 60 and diff.seconds < 3600:
            minutes = math.floor(diff.seconds/60)

            if minutes == 1:
                return str(minutes) + " m."

            else:
                return str(minutes) + " m."

        if diff.days == 0 and diff.seconds >= 3600 and diff.seconds < 86400:
            hours = math.floor(diff.seconds/3600)

            if hours == 1:
                return str(hours) + " hr."

            else:
                return str(hours) + " hrs."

        # 1 day to 30 days
        if diff.days >= 1 and diff.days < 30:
            days = diff.days

            if days == 1:
                return str(days) + " day"

            else:
                return str(days) + " days"

        if diff.days >= 30 and diff.days < 365:
            months = math.floor(diff.days/30)

            if months == 1:
                return str(months) + " month ago"

            else:
                return str(months) + " months ago"

        if diff.days >= 365:
            years = math.floor(diff.days/365)

            if years == 1:
                return str(years) + " yr"

            else:
                return str(years) + " years ago"


@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].author)
    kwargs['instance'].slug = slug


class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = CloudinaryField('image')

    class Meta:
        verbose_name_plural = "Images"

    def __str__(self):
        return self.post.body + ' Image'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    photo = models.ImageField(blank=True, null=True)

    def __str__(self):
        return "Profile of User {}".format(self.user.username)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', null=True,
                              related_name='replies', on_delete=models.CASCADE)
    content = models.TextField(max_length=160)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(str(self.user.username))

app/templates/detail.html
{% load static %}
{% load crispy_forms_tags %}
{% load cloudinary %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="feed">

        <div class="post">
            <div class="post__top">
                {% if post.author.profile.photo %}
                <img src="{{ post.author.profile.photo.url }}" alt="" class="post__avatar">
                {% else %}
                <img src="/media/default.jpg" alt="" class="post__avatar">
                {% endif %}
                <!-- <i class="far fa-user-circle" class="post__avatar"></i> -->
                <div class="post__topInfo">
                    <h5> {{post.author}} </h5>
                    <p>{{ post.whenpublished }}</p>
                </div>
                {% if post.author == request.user %}
                <div class="post__buttons">
                    <div class="post__topInfoBtn">
                        <a href="{% url 'post_edit' id=post.id %}">
                            <Button type="submit" name="button" class="btn btn-outline-secondary">Edit</Button>
                        </a>
                    </div>
                    <div class="post__topInfoBtns">
                        <a href="{% url 'post_delete' id=post.id %}" id="delete">
                            <Button type="submit" name="button" class="btn btn-outline-secondary">Delete</Button>
                        </a>
                    </div>
                </div>
                {% endif %}
            </div>
            <div class="post__bottom">
                <p> {{post.body}} </p>
            </div>
            <div class="post__image">
                {% for post in post.images_set.all %}
                <img src="{{ post.image.url }}" alt="no image">
                {% endfor %}
            </div>

            <!-- <div id="like-sections" class="post__options">
                <div id="like-section" class="post__option">
                    <button name="post_id" id="like" value="{{ post.id }}" class="post__option">
                        <i class="fas fa-thumbs-up"></i>
                        <p>{{ total_likes }} Like{{ total_likes|pluralize }}</p>
                    </button>
                </div>
            </div> -->

            <div class="pst__options">
                <div class="p__option" id="like-sections">
                    <span class="span"><i class="fas fa-thumbs-up"></i></span>
                    <p> {{ post.total_likes }}</p>
                </div>
                <div class="p__option">
                    <p class="p">{{ comments.count }} Comment{{ comments|pluralize }}</p>
                </div>
            </div>

            <div class="post__options">
                <div id="like-section" class="post__option">
                    {% include 'app/like_section.html' %}
                </div>
                <div class="post__option">
                    <i class="far fa-comment-alt"></i>
                    <p>Comment</p>
                </div>
                <div class="post__option">
                    <i class="fas fa-share"></i>
                    <p>Share</p>
                </div>
                <div class="post__option">
                    <i class="far fa-user-circle"></i>
                    <p><i class="fas fa-sort-down"></i></p>
                </div>
            </div>

            <hr>
            {% if not post.restrict_comment %}
            <div class="container-fluid ml-3">
                {% include 'app/comments.html' %}
            </div>
            {% endif %}

        </div>

    </div>
</body>

</html>

app/templates/feed.html
{% load static %}
{% load cloudinary %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <div class="feed">

        <div class="storyReal">
    
            <div style="background-image: url(https://scontent.fnbo4-1.fna.fbcdn.net/v/t15.5256-10/s280x280/154967691_10158953089367713_6393035302505457242_n.jpg?_nc_cat=102&amp;ccb=1-3&amp;_nc_sid=1055be&amp;_nc_eui2=AeG5lsFumIoYMsBH8Y4KTauX4ksuo_p0le_iSy6j-nSV7yPYKLt7_UHsA_RFgM4LGJLAnKcnHWOutwkJy_WkPRxj&amp;_nc_ohc=iYtX-qdPz9UAX_dvJU2&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=7&amp;oh=c17b6f331a2ec890f5e6e742bc2d9234&amp;oe=606D0D15);"
                class="story">
                <img src="https://scontent.fnbo4-1.fna.fbcdn.net/v/t1.0-1/cp0/p40x40/122657611_10158549290052713_8471536878232826151_n.jpg?_nc_cat=1&amp;ccb=1-3&amp;_nc_sid=1eb0c7&amp;_nc_eui2=AeFihHEUINZUmzVUGsEfVOzhWpszheZeOqlamzOF5l46qWwDP-m0gjPai34g0bQB1Me9c4gTH5OedepaD1gSRevV&amp;_nc_ohc=DODmx4O1nAMAX_Jlu8h&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=27&amp;oh=eb6d37eb6e4c5df67ebf1f37c6e2b70b&amp;oe=606EC26D"
                    class="story__avatar" alt="">
                <h4>Arsenal</h4>
            </div>
            <div style="background-image: url(https://scontent.fnbo4-1.fna.fbcdn.net/v/t15.5256-10/s280x280/154967691_10158953089367713_6393035302505457242_n.jpg?_nc_cat=102&amp;ccb=1-3&amp;_nc_sid=1055be&amp;_nc_eui2=AeG5lsFumIoYMsBH8Y4KTauX4ksuo_p0le_iSy6j-nSV7yPYKLt7_UHsA_RFgM4LGJLAnKcnHWOutwkJy_WkPRxj&amp;_nc_ohc=iYtX-qdPz9UAX_dvJU2&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=7&amp;oh=c17b6f331a2ec890f5e6e742bc2d9234&amp;oe=606D0D15);"
                class="story">
                <img src="https://scontent.fnbo4-1.fna.fbcdn.net/v/t1.0-1/cp0/p40x40/122657611_10158549290052713_8471536878232826151_n.jpg?_nc_cat=1&amp;ccb=1-3&amp;_nc_sid=1eb0c7&amp;_nc_eui2=AeFihHEUINZUmzVUGsEfVOzhWpszheZeOqlamzOF5l46qWwDP-m0gjPai34g0bQB1Me9c4gTH5OedepaD1gSRevV&amp;_nc_ohc=DODmx4O1nAMAX_Jlu8h&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=27&amp;oh=eb6d37eb6e4c5df67ebf1f37c6e2b70b&amp;oe=606EC26D"
                    class="story__avatar" alt="">
                <h4>Arsenal</h4>
            </div>
            <div style="background-image: url(https://scontent.fnbo4-1.fna.fbcdn.net/v/t15.5256-10/s280x280/154967691_10158953089367713_6393035302505457242_n.jpg?_nc_cat=102&amp;ccb=1-3&amp;_nc_sid=1055be&amp;_nc_eui2=AeG5lsFumIoYMsBH8Y4KTauX4ksuo_p0le_iSy6j-nSV7yPYKLt7_UHsA_RFgM4LGJLAnKcnHWOutwkJy_WkPRxj&amp;_nc_ohc=iYtX-qdPz9UAX_dvJU2&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=7&amp;oh=c17b6f331a2ec890f5e6e742bc2d9234&amp;oe=606D0D15);"
                class="story">
                <img src="https://scontent.fnbo4-1.fna.fbcdn.net/v/t1.0-1/cp0/p40x40/122657611_10158549290052713_8471536878232826151_n.jpg?_nc_cat=1&amp;ccb=1-3&amp;_nc_sid=1eb0c7&amp;_nc_eui2=AeFihHEUINZUmzVUGsEfVOzhWpszheZeOqlamzOF5l46qWwDP-m0gjPai34g0bQB1Me9c4gTH5OedepaD1gSRevV&amp;_nc_ohc=DODmx4O1nAMAX_Jlu8h&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=27&amp;oh=eb6d37eb6e4c5df67ebf1f37c6e2b70b&amp;oe=606EC26D"
                    class="story__avatar" alt="">
                <h4>Arsenal</h4>
            </div>
            <div style="background-image: url(https://scontent.fnbo4-1.fna.fbcdn.net/v/t15.5256-10/s280x280/154967691_10158953089367713_6393035302505457242_n.jpg?_nc_cat=102&amp;ccb=1-3&amp;_nc_sid=1055be&amp;_nc_eui2=AeG5lsFumIoYMsBH8Y4KTauX4ksuo_p0le_iSy6j-nSV7yPYKLt7_UHsA_RFgM4LGJLAnKcnHWOutwkJy_WkPRxj&amp;_nc_ohc=iYtX-qdPz9UAX_dvJU2&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=7&amp;oh=c17b6f331a2ec890f5e6e742bc2d9234&amp;oe=606D0D15);"
                class="story">
                <img src="https://scontent.fnbo4-1.fna.fbcdn.net/v/t1.0-1/cp0/p40x40/122657611_10158549290052713_8471536878232826151_n.jpg?_nc_cat=1&amp;ccb=1-3&amp;_nc_sid=1eb0c7&amp;_nc_eui2=AeFihHEUINZUmzVUGsEfVOzhWpszheZeOqlamzOF5l46qWwDP-m0gjPai34g0bQB1Me9c4gTH5OedepaD1gSRevV&amp;_nc_ohc=DODmx4O1nAMAX_Jlu8h&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=27&amp;oh=eb6d37eb6e4c5df67ebf1f37c6e2b70b&amp;oe=606EC26D"
                    class="story__avatar" alt="">
                <h4>Arsenal</h4>
            </div>
            <div style="background-image: url(https://scontent.fnbo4-1.fna.fbcdn.net/v/t15.5256-10/s280x280/154967691_10158953089367713_6393035302505457242_n.jpg?_nc_cat=102&amp;ccb=1-3&amp;_nc_sid=1055be&amp;_nc_eui2=AeG5lsFumIoYMsBH8Y4KTauX4ksuo_p0le_iSy6j-nSV7yPYKLt7_UHsA_RFgM4LGJLAnKcnHWOutwkJy_WkPRxj&amp;_nc_ohc=iYtX-qdPz9UAX_dvJU2&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=7&amp;oh=c17b6f331a2ec890f5e6e742bc2d9234&amp;oe=606D0D15);"
                class="story">
                <img src="https://scontent.fnbo4-1.fna.fbcdn.net/v/t1.0-1/cp0/p40x40/122657611_10158549290052713_8471536878232826151_n.jpg?_nc_cat=1&amp;ccb=1-3&amp;_nc_sid=1eb0c7&amp;_nc_eui2=AeFihHEUINZUmzVUGsEfVOzhWpszheZeOqlamzOF5l46qWwDP-m0gjPai34g0bQB1Me9c4gTH5OedepaD1gSRevV&amp;_nc_ohc=DODmx4O1nAMAX_Jlu8h&amp;_nc_ht=scontent.fnbo4-1.fna&amp;tp=27&amp;oh=eb6d37eb6e4c5df67ebf1f37c6e2b70b&amp;oe=606EC26D"
                    class="story__avatar" alt="">
                <h4>Arsenal</h4>
            </div>
    
        </div>

        <div class="messageSender">
            <div class="messageSender__top">
                {% if request.user.profile.photo %}
                <img src="{{ request.user.profile.photo.url }}" alt="" class="post__avatar">
                {% else %}
                <img src="/media/default.jpg" alt="" class="post__avatar">
                {% endif %}
                <!-- <i class="far fa-user-circle"></i> -->
                <form>
                    <input type="text" placeholder="What's on your mind {{request.user.username}}?" class="messageSender__input" />
                    <!-- <input type="text" placeholder="image URL (Optional)" /> -->
                    <button type="submit">Submit</button>
                </form>
            </div>
            <hr>
            <div class="messageSender__bottom">
                <div class="messageSender__option">
                    <i class="fab fa-youtube" style=" color: red "></i>
                    <h6>Live Video</h6>
                </div>
                <div class="messageSender__option">
                    <i class="far fa-images" style=" color: green"></i>
                    <h6>Photo/Video</h6>
                </div>
                <div class="messageSender__option">
                    <i class="far fa-laugh-wink" style="color: yellow;"></i>
                    <h6>Feeling/Activity</h6>
                </div>
            </div>
        </div>

        <div class="messageSender">
            <div class="messageSender__top">
        
                <div class="room">
                    <i class="fas fa-video fa-gradient"></i>
                    <input type="text" placeholder=" Create Room" class="messageSender__input" />
                </div>
                {% for profile in profiles %}
                    {% if profile.photo %}
                    <img src="{{ profile.photo.url }}" alt="" class="profile__avatar">
                    {% else %}
                    <img src="/media/default.jpg" alt="" class="profile__avatar">
                    {% endif %}
                {% endfor %}
                
            </div>
        </div>

        {% for post in posts %}
        <div class="post">
            <div class="post__top">
                <a href="{{post.get_absolute_url}}">
                    {% if post.author.profile.photo %}
                    <img src="{{ post.author.profile.photo.url }}" alt="" class="post__avatar">
                    {% else %}
                    <img src="/media/default.jpg" alt="" class="post__avatar">
                    {% endif %}
                </a>
                    <!-- <i class="far fa-user-circle" class="post__avatar"></i> -->
                <div class="post__topInfo">
                    <h5> {{post.author}} </h5>
                    <!-- <p>{{post.created}}</p> -->
                    <p>{{ post.whenpublished }}</p>
                </div>
            </div>
            <div class="post__bottom">
                <p> {{post.body}} </p>
            </div>
            <div class="post__image">
                <a href="{{post.get_absolute_url}}">
                    {% for post in post.images_set.all %}
                    <img src="{{ post.image.url }}" alt="no image">
                    {% endfor %}
                </a>
            </div>
            <!-- {% if post.total_likes > 0 %} -->
            <div class="pst__options">
                <div class="p__option">
                    <span class="span"><i class="fas fa-thumbs-up"></i></span>
                    <p>{{ post.total_likes }}</p>
                </div>
                <div class="p__option">
                    <p class="p">{{ post.comments.count }} Comment{{ post.comments|pluralize }}</p>
                </div>
            </div>
            <!-- {% else %}
            <div class="pst__options">
                <div class="p__option"> -->
                    <!-- <span class="span"><i class="fas fa-thumbs-up"></i></span> -->
                    <!-- <p></p>
                </div> -->
                <!-- <div class="p__option">
                    <p class="p">1 comment</p>
                </div>
            </div> -->
            <!-- {% endif %} -->
            <div class="post__options">
                <!-- <div id="like_sections" class="post__option">
                    {% include 'app/like.html' %}
                </div> -->
                <div class="post__option">
                    <i class="far fa-thumbs-up"></i>
                    <p>Like</p>
                </div>
                <div class="post__option">
                    <i class="far fa-comment-alt"></i>
                    <p>Comment</p>
                </div>
                <div class="post__option">
                    <i class="fas fa-share"></i>
                    <p>Share</p>
                </div>
                <div class="post__option">
                    <i class="far fa-user-circle"></i>
                    <p><i class="fas fa-sort-down"></i></p>
                </div>
            </div>
        
        </div>
        {% empty %}
        <div class="post">
            <h4> No post found for the Search '{{ request.GET.q }}' </h4>
        </div>
        {% endfor %}
        
        <div class="post">
            <div class="post__top">
                <i class="far fa-user-circle" class="post__avatar"></i>
                <div class="post__topInfo">
                    <h5> Jay Filch </h5>
                    <p>timestring...</p>
                </div>
            </div>
            <div class="post__bottom">
                <p> Lorem ipsum dolor, sit amet consectetur a
                    dipisicing elit. Alias, suscipit. </p>
            </div>
            <div class="post__image">
                <img src="{% static 'images/emg.jpg' %}" alt="" />
            </div>
            <div class="post__options">
                <div class="post__option">
                    <i class="far fa-thumbs-up"></i>
                    <p>Like</p>
                </div>
                <div class="post__option">
                    <i class="far fa-comment-alt"></i>
                    <p>Comment</p>
                </div>
                <div class="post__option">
                    <i class="fas fa-share"></i>
                    <p>Share</p>
                </div>
                <div class="post__option">
                    <i class="far fa-user-circle"></i>
                    <p><i class="fas fa-sort-down"></i></p>
                </div>
            </div>
        
        </div>
        
        <div class="post">
        
            <div class="post__top">
                <i class="far fa-user-circle" class="post__avatar"></i>
                <div class="post__topInfo">
                    <h5> Jay Filch </h5>
                    <p>timestring...</p>
                </div>
            </div>
            <div class="post__bottom">
                <p> Lorem ipsum dolor, sit amet consectetur a
                    dipisicing elit. Alias, suscipit. </p>
            </div>
            <div class="post__image">
                <img src="{% static 'images/Eagle.jpg' %}" alt="" />
            </div>
            <div class="post__options">
                <div class="post__option">
                    <i class="far fa-thumbs-up"></i>
                    <p>Like</p>
                </div>
                <div class="post__option">
                    <i class="far fa-comment-alt"></i>
                    <p>Comment</p>
                </div>
                <div class="post__option">
                    <i class="fas fa-share"></i>
                    <p>Share</p>
                </div>
                <div class="post__option">
                    <i class="far fa-user-circle"></i>
                    <p><i class="fas fa-sort-down"></i></p>
                </div>
            </div>
        
        </div>

    </div>
    
</body>
</html>

app/templates/index.html
{% extends 'app/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {{ block.super }}

    {% if request.user.is_authenticated %}
    <div class="app__body">
    
    
    
        {% include 'sidebar.html' %}
        {% include 'feed.html' %}
        {% include 'widget.html' %}
    
    
    </div>
    {% else %}
    
    {% include 'app/fb_login.html' %}
    
    {% endif %}
    
    {% endblock %}

</body>
</html>

app/templates/sidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="sidebar">
        <div class="sidebarRow">
            {% if request.user.profile.photo %}
            <img src="{{ request.user.profile.photo.url }}" alt="" class="nav-img">
            {% else %}
            <img src="/media/default.jpg" alt="" class="nav-img">
            {% endif %}
            <!-- <i class="far fa-user-circle"></i> -->
            <h6>{{request.user}}</h6>
        </div>
        <div class="sidebarRow">
            <i class="fab fa-font-awesome-flag"></i>
            <h6>Pages</h6>
        </div>
        <div class="sidebarRow">
            <i class="fas fa-stethoscope"></i>
            <h6>Covid-19 Info Center</h6>
        </div>
        <div class="sidebarRow">
            <i class="fas fa-user-friends"></i>
            <h6>Friends</h6>
        </div>
        <div class="sidebarRow">
            <span class="span"><i class="fas fa-users"></i></span>
            <h6>Groups</h6>
        </div>
        <div class="sidebarRow">
            <i class="fas fa-store"></i>
            <h6>MarketPlace</h6>
        </div>
        <div class="sidebarRow">
            <i class="fab fa-youtube"></i>
            <h6>Watch</h6>
        </div>
        <div class="sidebarRow">
            <span><i class="fas fa-angle-down"></i></span>
            <h6>See More</h6>
        </div>
    </div>
</body>
</html>

app/templates/widget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="widgets">
        <iframe title='fb'
            src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FaddifferenceJewellery%2F&tabs=timeline&width=270&height=900&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId"
            width="340" height="500" style="border: none; overflow: hidden;" scrolling="no" frameborder="0"
            allowfullscreen="true"
            allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
    </div>
</body>
</html>